#include <avr/io.h>
#include <util/delay.h>
#include <math.h>
#include <avr/interrupt.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "./motor.h"
#include "./usart.h"
#include "./communication.h"
#include "./other.h"
#include "./adc.h"
